name: Model Training and Evaluation Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GitActions/requirements.txt

      - name: Train Model
        run: |
          python GitActions/src/models/train_model.py

      - name: Evaluate Model
        run: |
          python GitActions/src/models/evaluate_model.py

      - name: Commit updated model and metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add GitActions/models GitActions/metrics || echo "Nothing to add"
          git commit -m "Auto-update: trained and evaluated model [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main || echo "No changes to push"

      - name: Workflow Complete
        run: echo "Model training & evaluation pipeline completed."
